### PR TITLE
Overhaul and overall improvement of GodotBigNumberClass

### PR DESCRIPTION
**Pull request by TehAwesomestKitteh**
Summary of changes:

- Separated `Big.gd` and `Big.gd4` into `Godot 3.x/Big.gd` and `Godot 4.1.x/Big.gd` (since `.gd` is the official script extension, not `.gd4`)
- Made both classes follow the [GDScript Style Guide](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html)
- Fixed words, spelling, and English names
- Overhauled the `4.1.x` class:
  - Added more methods to cover more operations (mainly the non-assignment operators, `+`, `-`, `*`, and `/`)
  - Added near-complete documentation of all the variables and methods
  - Improved overall readability of the class
  - Improved, shortened, or optimized various statements
  - Fixed (or suppressed) all warnings. No Project Settings modifying needed anymore
  - Operations no longer modify Big numbers by default (modification done by "Equals" assignment methods instead)
  - `other` is now `options`, and various options has had their defaults adjusted

`toAA` and the `suffixes_aa` have also been marked `@deprecated`, pending a re-write so that it's faster

### CODE REVIEW

**Comment by Drillur** [comment]
I required this for my game and figured I should share it with someone who cares about the Big class!

This gets a random number between `min` and `max`.
```
static func get_random_point(min: Big, max: Big) -> Big:
	if min.isEqualTo(max):
		return max
	var random_mantissa = randf_range(min.mantissa, max.mantissa)
	var random_exponent = randi_range(min.exponent, max.exponent)
	return Big.new(random_mantissa, random_exponent)
```

Not related: maybe you should convert the method names to snake_case to fit in with Godot's style guide. But not important!

**Comment by ChronoDK** [comment]
> I required this for my game and figured I should share it with someone who cares about the Big class!
> 
> This gets a random number between `min` and `max`.
> 
> ```
> static func get_random_point(min: Big, max: Big) -> Big:
> 	if min.isEqualTo(max):
> 		return max
> 	var random_mantissa = randf_range(min.mantissa, max.mantissa)
> 	var random_exponent = randi_range(min.exponent, max.exponent)
> 	return Big.new(random_mantissa, random_exponent)
> ```
> 
> Not related: maybe you should convert the method names to snake_case to fit in with Godot's style guide. But not important!

Cool addition, but I think that function can be improved. There will be no mantissa range if min and max have the same mantissa.

**Comment by Drillur** [comment]
Wait, hang on! Your reply made me realize a problem: If you do get_random_point(Big.new(4), Big.new(40)), it can only be 4 or 40, because mantissa will not change but exponent can. I'll try to work on a solution

**Comment by Drillur** [comment]
Oh, hell, I currently can't get it to work. This is nightmarish. And I just know the solution will be so simple and easy that it'll make me mad. Good lord

**Comment by Drillur** [comment]
I give up. This works for numbers less than e308:
```
static func get_random_point(min: Big, max: Big) -> Big:
	# Ensure min is less than or equal to max
	if min.greater(max):
		var temp = min
		min = max
		max = temp
	
	if min.exponent == max.exponent:
		return Big.new(randf_range(min.mantissa, max.mantissa), max.exponent)
	
	if min.less(1.79769e308) and max.less(1.79769e308):
		return Big.new(randf_range(min.toFloat(), max.toFloat()))
	else:
		print("Cry")
		return Big.new(1)
```

**Pull request merged**
